apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  AUTH_SVC_ADDRESS: "auth-psd2:5000"
  FOOD_WASTE_GATEWAY_QUEUE: "foodwaste_gateway"
  FOOD_WASTE_FOODWASTE_QUEUE: "foodwaste_foodwaste"
