apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <match **>
      @type logstash
      host <LOGSTASH_HOST>
      port <LOGSTASH_PORT>
      tag kubernetes.*
    </match>
