apiVersion: v1
kind: ConfigMap
metadata:
  name: foodwaste-configmap
data:
  MYSQL_HOST: host.minikube.internal
  MYSQL_USER: psd2_user
  MYSQL_DB: foodwaste
  MYSQL_PORT: "3306"
  FOOD_WASTE_GATEWAY_QUEUE: "foodwaste_gateway"
  FOOD_WASTE_FOODWASTE_QUEUE: "foodwaste_foodwaste"
  FOODWASTE_SVC_ADDRESS: "foodwaste-psd2:8000"