apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodwaste-psd2
  labels: 
    app: foodwaste-psd2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: foodwaste-psd2
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: foodwaste-psd2
    spec:
      containers:
        - name: foodwaste-psd2
          image: shunyaoteo99/foodwaste_psd2
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: foodwaste-configmap
            - secretRef:
                name: foodwaste-secret